spring:
  profiles: local
  batch:
    initialize-schema: always
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?charcaterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: diofc2473
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      format-sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: update

--- #local 환경
spring:
  profiles: local
    logging:
      level:
      root: info

--- #dev 환경
spring:
  profiles: dev
    logging:
      level:
        root: info

--- #prod 환경
spring:
  profiles: prod
server:
  port: 9090
  logging:
    level:
      root: error
