spring:
  profiles:
    active: local
  batch:
    initialize-schema: always
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?charcaterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: diofc2473
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      format-sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: update
  cache:
    type:
      redis
  redis:
    host:
      localhost
    port:
      6379

token:
  header: Authorization
  signkey: secret

redis:
  gubun:
    name: SHOP

logging:
  level:
    root: info

file:
  download:
    path: /Users/obyeong-gwon/downloads/excel
  upload:
    path: /Users/obyeong-gwon/downloads/excel/tmp